config/routes.rb
Rails.application.routes.draw do
  get 'project/index'
  root to: 'pages#index'
  resources :sessions, only: [:update]
  resources :projects
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability

  include CanCan::Ability

  def initialize(user)

    user ||= User.new

    # Admin User has full access everywhere
    if user.role?(:admin)
      can :manage, :all
    elsif user.role?(:moderator) # Moderator Role can create and read Projects
      #can [:create, :read, :update], Project
      # can [:create, :read, :update], [Project, Task]
      can :create, Project
      can :update, Project do |project|
        project.ongoing?
      end
      can :read, Project
    elsif user.role?(:user) # User Role just can read Projects
      #can :read, Project
      can :read, Project, ongoing: true
    end

  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
end

app/models/user.rb
class User
  ROLES = {0 => :guest, 1 => :user, 2 => :moderator, 3 => :admin}

  attr_reader :role

  def initialize(role_id = 0)
    @role = ROLES.has_key?(role_id.to_i) ? ROLES[role_id.to_i] : ROLES[0]
  end

  def role?(role_name)
    role == role_name
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  check_authorization

  rescue_from CanCan::AccessDenied do |exception|
    flash[:warning] = exception.message
    redirect_to root_path
  end

  private

  def current_user
    User.new(session[:id])
  end

  helper_method :current_user
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  skip_authorization_check

  def index
  end
  
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  before_action :load_projects, only: :index
  load_and_authorize_resource

  def index
    # @projects = Project.all
    # authorize! :index, @project
  end

  def new
    # @project = Project.new
    # authorize! :new, @project
  end

  def create
    # @project = Project.new(project_params)
    if @project.save
      flash[:success] = 'Project was saved!'
      redirect_to root_path
    else
      render 'new'
    end
    # authorize! :create, @project
  end
  
  
  def edit
    # @project = Project.find(params[:id])
    # authorize! :edit, @project
  end
  
  def update
    # @project = Project.find(params[:id])
    if @project.update_attributes(project_params)
      flash[:success] = 'Project was updated!'
      redirect_to root_path
    else
      render 'edit'
    end
    # authorize! :update, @project
  end
  
  def destroy
    #@project = Project.find(params[:id])
    if @project.destroy
      flash[:success] = 'Project was destroyed!'
    else
      flash[:warning] = 'Cannot destroy this project...'
    end
    redirect_to root_path
    # authorize! :destroy, @project
  end

  private
  
  def project_params
    params.require(:project).permit(:title, :ongoing)
  end

  def load_projects
    @projects = Project.accessible_by(current_ability).order('created_at DESC')
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  skip_authorization_check

  def update
    id = params[:id].to_i
    session[:id] = User::ROLES.has_key?(id) ? id : 0
    flash[:success] = "Your new role #{User::ROLES[id]} was set!"
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/project_helper.rb
module ProjectHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>iCan</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-inverse">
      <div class="container">
        <div class="navbar-header">
          <%= link_to 'iCan', root_path, class: 'navbar-brand' %>
        </div>
        <div id="navbar">
          <ul class="nav navbar-nav">
          </ul>

          <ul class="nav navbar-nav pull-right">
            <li class="dropdown">
              <a class="dropdown-toggle" aria-expanded="false" role="button" data-toggle="dropdown" href="#">
                Role
                <span class="caret"></span>
              </a>
              <ul class="dropdown-menu" role="menu">
                <% User::ROLES.each do |k, v| %>
                  <li>
                    <%= link_to session_path(k), method: :patch do %>
                      <%= v %>
                      <% if v == current_user.role %>
                        <small class="text-muted">(current)</small>
                      <% end %>
                    <% end %>
                  </li>
                <% end %>
              </ul>
            </li>
          </ul>
          <ul class="nav navbar-nav">
            <% if can? :create, Project %>
              <li><%= link_to 'Add Project', new_project_path %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>

    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>">
          <%= value %>
        </div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/index.html.erb
<div class="page-header"><h1>Welcome!</h1></div>

<% if can? :index, Project %>
  <%= link_to 'Projects', projects_path, class: 'btn btn-lg btn-primary' %>
<% end %>

app/views/projects/_form.html.erb
<%= form_for @project do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :ongoing %>
    <%= f.check_box :ongoing %>
  </div>

  <%= f.submit 'Post', class: 'btn btn-primary' %>
<% end %>

app/views/projects/edit.html.erb
<div class="page-header"><h1>Edit Project</h1></div>

<%= render 'form' %>

app/views/projects/index.html.erb
<div class="page-header"><h1>Projects</h1></div>

<% @projects.each do |project| %>
  <div class="well well-sm">
    <h2><%= project.title %></h2>
    <% if can? :update, project %>
      <%= link_to 'Edit', edit_project_path(project), class: 'btn btn-info' %>
    <% end %>

    <% if can? :destroy, project %>
      <%= link_to 'Delete', project_path(project), class: 'btn btn-danger', method: :delete, data: {confirm: 'Are you sure?'} %>
    <% end %>
  </div>
<% end %>

app/views/projects/new.html.erb
<div class="page-header"><h1>New Project</h1></div>

<%= render 'form' %>